apiVersion: v1
kind: Service
metadata:
  name: glusterfs-exporter-{{ $(address).split(".")[-1] }}
  labels:
    k8s-app: glusterfs-exporter
    app: glusterfs-exporter
spec:
 type: ExternalName
 externalName: {{ address }}
 clusterIP: ""
 ports:
 - name: http-metrics
   port: 9189
   targetPort: 9189
   protocol: TCP
