apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-exporter-{{ $(address).split(".")[-1] }}
  labels:
    k8s-app: glusterfs-exporter
subsets:
- addresses:
  - ip: {{ address }}
  ports:
  - name: http-metrics
    port: 9189
    protocol: TCP