apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: glusterfs-exporter
  labels:
    k8s-app: glusterfs-exporter
  namespace: monitoring
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: glusterfs-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: http-metrics
    interval: 30s
